#include <Python.h>

extern PyObject* lightship_error;

void
create_lightship_exceptions(PyObject* module);
